### ISSUE TITLE
Twitter profile pages won't fully load.

### ISSUE THREAD

**Issue by Handmedown222** [Bl4Cc4t/GoodTwitter2#212]
Suddenly an hour ago, any Twitter profile page including my own, will only show a couple of items, no banner, no profile write up, and no tweets. Tried refreshing, clearing cache, and checking other sites which do load fully. My notification and home pages load and I can open up individual tweets on new tabs. I can also go to Twitter using Firefox browser and all pages load correctly. It's only on Chrome where I have this app. 

![image](https://user-images.githubusercontent.com/68014036/97052941-8e592400-1547-11eb-907b-5e7ea27065de.png)

**Please check the following before you continue**
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuation**
 - Browser (e.g. Chrome 83)
 - Userscript Manager (e.g. Tampermonkey v4.10)

**Comment by Handmedown222** [comment]
Ok, what does "fixed in dev" mean? A fix is in development or it's already fixed, and do I need to do anything? Thank you.

**Comment by AmigaGPU** [comment]
I can confirm this bug, my extensions are in dev mode and it still does not load. I detected this error a couple of hours ago

Chrome latest version, Linux. It happens in both beta and regular extension of Tampermonkey

**Comment by Bl4Cc4t** [comment]
@Handmedown222
> Ok, what does "fixed in dev" mean? A fix is in development or it's already fixed, and do I need to do anything? Thank you.

`fixed in dev` means that the fix is already merged into the dev branch. I'll rename it to `fixed in dev branch` to clarify that I guess.
I'Il will release a new version in a few hours, you don't have to do anything other than have a bit patience :)


@AmigaGPU 
> I can confirm this bug, my extensions are in dev mode and it still does not load.

I'm not sure what "dev mode" is, but as I said it's already fixed. Just wait a bit.

**Comment by Poopooracoocoo** [comment]
>I can confirm this bug, my extensions are in dev mode and it still does not load.
>>I'm not sure what "dev mode" is, but as I said it's already fixed. Just wait a bit.

I think AmigaGPU meant that they enabled Chrome's developer mode for extensions. just to clarify for any future misunderstandings :)
