### ISSUE TITLE
Clicking Home no longer brings you to the top of the page

### ISSUE THREAD

**Issue by NoThanksPal** [Bl4Cc4t/GoodTwitter2#302]
Prior to today's update, if I scrolled down in Twitter, I could click the top left HOME button and it would bring the page back to the top, refreshed with any new tweets.  That doesn't seem to happen now, although it does occasionally, usually if I haven't scrolled down very far.

 - Chrome 90
 - Tampermonkey v4.13

**Comment by CreepasCraft** [comment]
Ah I thought that was just me

**Comment by AlbertoBal** [comment]
If you have the main "Hide follow suggestions" setting checked clicking Home brings you to the top of the page but the line of text that shows which account retweeted a tweet disappears.
If you have the main "Hide follow suggestions" setting unchecked you can see the retweet line but then clicking Home don't bring you to the top of the page.

**Comment by NoThanksPal** [comment]
If I have 'Hide Follow Suggestions" checked or unchecked, clicking 'Home' still doesn't bring me back to the top of the page.

**Comment by geyerbri** [comment]
I have this problem too. Toggling "Hide Follow Suggestions" does not help (whether checked or unchecked).

Maybe repeat of #229?

**Comment by wing0csutom** [comment]
'm also suffering from this phenomenon, the previous fix doesn't seem to work.

**Comment by LaurentChemla** [comment]
Still not resolved in v0.0.31

**Comment by wing0csutom** [comment]
It seems that one of the two parts corrected in # 229 has returned to its original state.  
It worked correctly when I manually rewrote the following parts.

      // prevent auto scroll to top
      if (prev > 1500 && curr == 0) {

  ↓↓↓

      // prevent auto scroll to top on /search and /explore
      if (prev > 1500 && curr == 0 && getPath().match(/^(?:search\?|explore\/?$)/)) {

**Comment by geyerbri** [comment]
I submitted a pull request to reinstate this fix: #336

**Comment by Bl4Cc4t** [comment]
Thanks for all your contributions to this issue and also for being so patient.
Especially @wing0csutom & @geyerbri!

I merged the fix.

**Comment by NoThanksPal** [comment]
Does the fix work for anyone else?  Clicking on 'Home' still does nothing here, in terms of bringing me back to the top of the feed.  Thanks.
