### ISSUE TITLE
Translate button missing

### ISSUE THREAD

**Issue by Harumoon** [Bl4Cc4t/GoodTwitter2#419]
**Please check the following before you continue**
- [x] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [x] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [x] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.

**Your configuration**
 - Browser (e.g. Chrome 83)
 - Userscript Manager (e.g. Tampermonkey v4.10)

**Comment by Harumoon** [comment]
![Capture](https://user-images.githubusercontent.com/101605071/158273258-5ec59225-e6a4-448c-8be0-4b085ded0a3a.PNG)

**Comment by Harumoon** [comment]
It's the same on both Firefox 98.0.1 and ESR 91.7.1
and both the latest Tampermonkey and Violent Monkey. 
Everything else is as normal, there's just no Translate button until you actually click the individual Tweets, which is just how it works without GT2 anyway. So for whatever reason the Translate button disappeared a few days ago, about 12.3.2022.

**Comment by Bl4Cc4t** [comment]
Hm, I don't have that issue, it shows up for me on all tweets. Using firefox 98.0.1.

Maybe they changed something internally and the change isn't on all users ends?
Just to be safe, the option "Hide “Translate Tweet” button" isn't activated, right?

**Comment by Harumoon** [comment]
Hi, no the 'Hide Translate Button' setting is not selected. Yes, maybe Twitter changed something for certain users or something weird...but the rest of GT2 is still working as normal so who knows? For the moment I just have to highlight the tweets and use the Simple Translate extension...but that's a bit of a pain compared to just clicking that button. Opening each tweet individually just to access the translate button is even more of a bother though.

**Comment by Bl4Cc4t** [comment]
That's weird. Do you get any errors in the console? To access the console, press F12 and switch to the "console" tab.

---

I can try to fix it, but I need your help. Please do the following:
- right click on any tweet that should have the translate button
- choose "Inspect"
- it should look like this now: 
![image](https://user-images.githubusercontent.com/6740726/158853383-749b1c42-858f-4e90-a3f1-527dcc22b16e.png)
- navigate to the yellow marked node of the tweet
- right click the node, choose "Copy -> Outer HTML"
- paste the result here, preferably wrapped inside a code block, like this:
````
  ```content```
  ````

**Comment by Harumoon** [comment]
Thanks, there are a few errors in the console, there are a few each of these listed there:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.twitter.com/1.1/jot/client_event.json. (Reason: CORS request did not succeed). 4

Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). 3 main.69f3b965.js:20:253463

TypeError: res.cards.players is undefined sandbox eval code:1891:62


When I right click on the tweet and select View Page Source [is that the same as 'Inspect'?] there's nothing like what you've highlighted in yellow as far as I can see.

**Comment by Bl4Cc4t** [comment]
You can make a screenshot of the console next time, makes it a bit easier. The yellow messages in the console are warnings and can be ignored, they have nothing to do with the script.

No, "view page source" is not the same as "inspect".  It's at the very bottom 
![image](https://user-images.githubusercontent.com/6740726/158978508-3c15efd1-d412-40b0-9bd7-b1d310207517.png)
This will show you the inspector in the same small window that opened when you pressed F12.

Also, it may be easier to if you switch the layout to the right, you can do that here: 
![image](https://user-images.githubusercontent.com/6740726/158978775-ed755a5b-5da6-48df-8edd-09ccffa1153b.png)

**Comment by Harumoon** [comment]
I don't have 'Inspect' in my right click menu, a long time ago I had someone show me how to remove a whole bunch of things there and that must have been one of them. I can access it from Tools-Web Developer Tools, that's fine for the whole page but if I click an actual Tweet the Translate button is there anyway, so I'm not sure what to do. Sorry, I'm totally out of my depth with all this sort of stuff.
Here are some screenshots anyway...the first two are the Errors part of my Twitter Home page, the last two are the Inspector part of a Japanese page which should have the Translate button on every tweet.

![Capture 1](https://user-images.githubusercontent.com/101605071/159091813-067f6d96-6611-45f9-9633-941b0106e215.PNG)

![Capture 2](https://user-images.githubusercontent.com/101605071/159091837-d2d7147e-6f05-4bd6-ac16-3c24fd79292c.png)

![Capture 3](https://user-images.githubusercontent.com/101605071/159091860-85bb5bf7-cf73-4108-af07-e1f2d95deb25.PNG)

![Capture 4](https://user-images.githubusercontent.com/101605071/159091868-8a458ce6-f974-4ef7-8b54-5269c7674988.PNG)

Another thing: If the person is quoting another tweet, the Translate button is there in that other tweet, it's just not in the person's tweet.
Like this:

![Capture 5](https://user-images.githubusercontent.com/101605071/159092180-444cd2db-df8a-4530-bcee-b5a6cf3d4df4.PNG)

**Comment by Bl4Cc4t** [comment]
You have... removed the "inspect" button? I have never heard of that before, that sounds a bit weird tbh

Then, instead of "inspect", please do the following:
- click on that button: 
![image](https://user-images.githubusercontent.com/6740726/159094038-2305a38e-7dca-4473-a3f0-891aa2c46c0b.png)

- manually select something within a tweet that should have the button
- proceed with step 3 from before
 
> Here are some screenshots anyway...the first two are the Errors part of my Twitter Home page, the last two are the Inspector part of a Japanese page which should have the Translate button on every tweet.
[The Errors are different today for whatever reason]

Hm, none of these errors are related to the script...

> Another thing: If the person is quoting another tweet, the Translate button is there in that other tweet, it's just not in the person's tweet.
Like this:

Interesting. That means it is at least partially working...

**Comment by Harumoon** [comment]
The right click menu is like this in my Firefox, I think it's because of the CSS thing I've been using for ages and I don't really want to try to change it because there's a ton of other stuff that I need in it...plus I don't really know what I'm doing with that.

![Untitled-01](https://user-images.githubusercontent.com/101605071/159114709-8f6704e5-70d7-463e-9e81-7e33204b99bd.jpg)

I think I managed the "Copy -> Outer HTML" thing from one of the tweets, that option suddenly became available...is this right?

```<div dir="auto" class="css-901oao r-18jsvk2 r-1tl8opc r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-bnwqim r-qvutc0" id="id__h3igq00nszs" lang="ja"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">MANAKO BIRTHDAY LIVE 2022
改めてありがとう！
無事終わり、雨も降りました来てくれてありがとう久しぶりに会えたりMANAKOで歌聞いてもらえたり幸せです明日もよろしくねーーっっっ^_^！</span></div>```

That's a tweet that should have the Translate button but doesn't.

**Comment by Harumoon** [comment]
Hmm, that looks completely different to what I pasted there?

<div dir="auto" class="css-901oao r-18jsvk2 r-1tl8opc r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-bnwqim r-qvutc0" id="id__h3igq00nszs" lang="ja"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">MANAKO BIRTHDAY LIVE 2022
改めてありがとう！
無事終わり、雨も降りました来てくれてありがとう久しぶりに会えたりMANAKOで歌聞いてもらえたり幸せです明日もよろしくねーーっっっ^_^！</span></div>

**Comment by Harumoon** [comment]
Hmm, that looks compeltely different to what I pasted there, most of it isn't there?

I'll try it as a Notepad txt file

[A.txt](https://github.com/Bl4Cc4t/GoodTwitter2/files/8308873/A.txt)

**Comment by Harumoon** [comment]
I'm obviously doing it wrong because there's never any yellow node whatever I do. 
Depending on how I try to position that blue 'select' thing on the tweet, if I scroll up a bit in the Inspector I can see a group of things that look the same as in your yellow example, but they're not yellow, they're all blue once I click on them. I'll paste the one of those that seems to be for this tweet anyway...

```<div style="transform: translateY(5763.43px); position: absolute; width: 100%; transition: opacity 0.3s ease-out 0s;"><div class="css-1dbjc4n r-j5o65s r-qklmqi r-1adg3ll r-1ny4l3l" data-gt2-divider-add-ignore=""><div class="css-1dbjc4n"><article aria-labelledby="id__wqppy5eg6bs id__fbnvf252qs6 id__kshcl7bstxe id__14mkrgncrvr id__05wd2so1kj3r id__i9zbcxsy1u id__9972v8eekt id__99wejvy7nkl id__gn8bgzvg07f id__b782g87bnm id__q1a99780ib9 id__xb6md9ckxyj id__6azr8km2b2q id__8jja1sbjwhi id__hqosci0mf3e" role="article" tabindex="0" class="css-1dbjc4n r-1loqt21 r-18u37iz r-1ny4l3l r-1udh08x r-qi0n3 r-c9eks5 r-o7ynqc r-6416eg" data-testid="tweet"><div class="css-1dbjc4n r-eqz5dr r-16y2uox r-1wbh5a2"><div class="css-1dbjc4n r-16y2uox r-1wbh5a2 r-1ny4l3l"><div class="css-1dbjc4n"><div class="css-1dbjc4n"><div class="css-1dbjc4n r-18u37iz"><div class="css-1dbjc4n r-1iusvr4 r-16y2uox r-19urhcx"><div class="css-1dbjc4n r-15zivkp r-q3we1"><div class="css-1dbjc4n r-18u37iz"><div class="css-1dbjc4n r-obd0qt r-h7e6lq r-18kxxzh r-1777fci r-1hbzrj0"><svg viewBox="0 0 24 24" aria-hidden="true" class="r-14j79pv r-4qtqp9 r-yyyyoo r-1hjwoze r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-12ym1je"><g><path d="M23.615 15.477c-.47-.47-1.23-.47-1.697 0l-1.326 1.326V7.4c0-2.178-1.772-3.95-3.95-3.95h-5.2c-.663 0-1.2.538-1.2 1.2s.537 1.2 1.2 1.2h5.2c.854 0 1.55.695 1.55 1.55v9.403l-1.326-1.326c-.47-.47-1.23-.47-1.697 0s-.47 1.23 0 1.697l3.374 3.375c.234.233.542.35.85.35s.613-.116.848-.35l3.375-3.376c.467-.47.467-1.23-.002-1.697zM12.562 18.5h-5.2c-.854 0-1.55-.695-1.55-1.55V7.547l1.326 1.326c.234.235.542.352.848.352s.614-.117.85-.352c.468-.47.468-1.23 0-1.697L5.46 3.8c-.47-.468-1.23-.468-1.697 0L.388 7.177c-.47.47-.47 1.23 0 1.697s1.23.47 1.697 0L3.41 7.547v9.403c0 2.178 1.773 3.95 3.95 3.95h5.2c.664 0 1.2-.538 1.2-1.2s-.535-1.2-1.198-1.2z"></path></g></svg></div><div class="css-1dbjc4n r-1iusvr4 r-16y2uox"><div class="css-1dbjc4n r-18u37iz"><div class="css-1dbjc4n r-1habvwh r-1wbh5a2 r-1777fci"><div class="css-1dbjc4n"><a href="/fleu_fleu" dir="auto" role="link" class="css-4rbku5 css-18t94o4 css-901oao r-14j79pv r-1loqt21 r-37j5jr r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-qvutc0" id="id__14mkrgncrvr"><span class="css-901oao css-16my406 css-cens5h r-14j79pv r-poiln3 r-1b43r93 r-b88u0q r-14yzgew r-bcqeeo r-qvutc0" style="-webkit-line-clamp: 2;" id="id__14mkrgncrvr" data-testid="socialContext"><span dir="ltr" class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">fleufleu</span></span> Retweeted</span></a></div></div></div></div></div></div></div></div></div><div class="css-1dbjc4n r-18u37iz"><div class="css-1dbjc4n r-1awozwy r-h7e6lq r-18kxxzh r-1hbzrj0"><div class="css-1dbjc4n r-18kxxzh r-1wbh5a2 r-13qz1uu"><div class="css-1dbjc4n r-1wbh5a2 r-dnmrzs"><div class="css-1dbjc4n r-1adg3ll r-1h3ijdo r-bztko3" style="width: 53px;" id="id__i9zbcxsy1u"><div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 100%;"></div><div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu"><div class="css-1dbjc4n r-1adg3ll r-1pi2tsx r-1wyvozj r-bztko3 r-u8s1d r-1v2oles r-desppf r-13qz1uu"><div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 100%;"></div><div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu"><div class="css-1dbjc4n r-sdzlij r-ggadg3 r-1udh08x r-u8s1d r-8jfcpp" style="height: calc(100% + 4px); width: calc(100% + 4px);"><a href="/Gt_kaho" role="link" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1niwhzg r-1loqt21 r-1pi2tsx r-1ny4l3l r-o7ynqc r-6416eg r-13qz1uu"><div class="css-1dbjc4n r-sdzlij r-1wyvozj r-1udh08x r-633pao r-u8s1d r-1v2oles r-desppf" style="height: calc(100% - 4px); width: calc(100% - 4px);"><div class="css-1dbjc4n r-1niwhzg r-1pi2tsx r-13qz1uu"></div></div><div class="css-1dbjc4n r-sdzlij r-1wyvozj r-1udh08x r-633pao r-u8s1d r-1v2oles r-desppf" style="height: calc(100% - 4px); width: calc(100% - 4px);"><div class="css-1dbjc4n r-14lw9ot r-1pi2tsx r-13qz1uu"></div></div><div class="css-1dbjc4n r-14lw9ot r-sdzlij r-1wyvozj r-1udh08x r-633pao r-u8s1d r-1v2oles r-desppf" style="height: calc(100% - 4px); width: calc(100% - 4px);"><div class="css-1dbjc4n r-1adg3ll r-1udh08x" style=""><div class="r-1adg3ll r-13qz1uu" style="padding-bottom: 100%;"></div><div class="r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-ipm5af r-13qz1uu"><div aria-label="" class="css-1dbjc4n r-1p0dtai r-1mlwlqe r-1d2f490 r-1udh08x r-u8s1d r-zchlnj r-ipm5af r-417010"><div class="css-1dbjc4n r-1niwhzg r-vvn4in r-u6sd8q r-4gszlv r-1p0dtai r-1pi2tsx r-1d2f490 r-u8s1d r-zchlnj r-ipm5af r-13qz1uu r-1wyyakw" style="background-image: url(&quot;https://pbs.twimg.com/profile_images/1472827345635790857/Q86DLqTl_x96.jpg&quot;);"></div><img alt="" draggable="true" src="https://pbs.twimg.com/profile_images/1472827345635790857/Q86DLqTl_x96.jpg" class="css-9pa8cd"></div></div></div></div><div class="css-1dbjc4n r-sdzlij r-1wyvozj r-1udh08x r-u8s1d r-1v2oles r-desppf" style="height: calc(100% - 4px); width: calc(100% - 4px);"><div class="css-1dbjc4n r-12181gd r-1pi2tsx r-1ny4l3l r-o7ynqc r-6416eg r-13qz1uu"></div></div></a></div></div></div></div></div></div></div></div><div class="css-1dbjc4n r-1iusvr4 r-16y2uox r-1777fci r-ig955"><div class="css-1dbjc4n"><div class="css-1dbjc4n r-zl2h9q"><div class="css-1dbjc4n r-k4xj1c r-18u37iz r-1wtj0ep"><div class="css-1dbjc4n r-1d09ksm r-18u37iz r-1wbh5a2"><div class="css-1dbjc4n r-1wbh5a2 r-dnmrzs r-1ny4l3l"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-1wbh5a2 r-dnmrzs r-1ny4l3l" id="id__05wd2so1kj3r"><div class="css-1dbjc4n r-1wbh5a2 r-dnmrzs"><a href="/Gt_kaho" role="link" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1loqt21 r-1ny4l3l"><div class="css-1dbjc4n r-1awozwy r-18u37iz r-dnmrzs"><div dir="auto" class="css-901oao r-1awozwy r-18jsvk2 r-6koalj r-37j5jr r-1inkyih r-b88u0q r-hbpseb r-bcqeeo r-1udh08x r-3s2u2q r-qvutc0"><span class="css-901oao css-16my406 css-bfa6kz r-poiln3 r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">つじかほ</span></span></div><div dir="auto" class="css-901oao r-18jsvk2 r-xoduu5 r-18u37iz r-1q142lx r-37j5jr r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-qvutc0"></div></div></a></div><div class="css-1dbjc4n r-18u37iz r-1wbh5a2 r-13hce6t"><div class="css-1dbjc4n r-1wbh5a2 r-dnmrzs"><a href="/Gt_kaho" role="link" tabindex="-1" class="css-4rbku5 css-18t94o4 css-1dbjc4n r-1loqt21 r-1wbh5a2 r-dnmrzs r-1ny4l3l"><div class="css-1dbjc4n"><div dir="ltr" class="css-901oao css-bfa6kz r-14j79pv r-18u37iz r-37j5jr r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">@Gt_kaho</span></div></div></a></div></div></div></div><div dir="auto" aria-hidden="true" class="css-901oao r-14j79pv r-1q142lx r-37j5jr r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-s1qlax r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">·</span></div><a href="/Gt_kaho/status/1505543284726571014" dir="auto" aria-label="Mar 21" role="link" class="css-4rbku5 css-18t94o4 css-901oao r-14j79pv r-1loqt21 r-1q142lx r-37j5jr r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-3s2u2q r-qvutc0" id="id__99wejvy7nkl"><time datetime="2022-03-20T13:54:25.000Z">Mar 21</time></a></div><div class="css-1dbjc4n r-uzqwk8"><div class="css-1dbjc4n r-1awozwy r-6koalj r-18u37iz"><div class="css-1dbjc4n"><div class="css-1dbjc4n r-18u37iz r-1h0z5md"><div aria-expanded="false" aria-haspopup="menu" aria-label="More" role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1777fci r-12sks89 r-1ny4l3l r-bztko3 r-lrvibr" data-testid="caret"><div dir="ltr" class="css-901oao r-1awozwy r-14j79pv r-6koalj r-37j5jr r-1inkyih r-16dba41 r-1h0z5md r-hbpseb r-bcqeeo r-o7ynqc r-clp7b1 r-3s2u2q r-qvutc0"><div class="css-1dbjc4n r-xoduu5"><div class="css-1dbjc4n r-1niwhzg r-sdzlij r-1p0dtai r-xoduu5 r-1d2f490 r-xf4iuw r-1ny4l3l r-u8s1d r-zchlnj r-ipm5af r-o7ynqc r-6416eg"></div><svg viewBox="0 0 24 24" aria-hidden="true" class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi"><g><circle cx="5" cy="12" r="2"></circle><circle cx="12" cy="12" r="2"></circle><circle cx="19" cy="12" r="2"></circle></g></svg></div></div></div></div></div></div></div></div></div></div><div class="css-1dbjc4n"><div dir="auto" class="css-901oao r-18jsvk2 r-1tl8opc r-1inkyih r-16dba41 r-hbpseb r-bcqeeo r-bnwqim r-qvutc0" id="id__b782g87bnm" lang="ja"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">渋谷GUILTYでした</span><img alt="🧚🏻‍♀️" draggable="false" src="https://abs-0.twimg.com/emoji/v2/svg/1f9da-1f3fb-200d-2640-fe0f.svg" title="Woman fairy" class="r-4qtqp9 r-dflpy8 r-sjv1od r-zw8f10 r-10akycc r-h9hxbl"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">わたし初箱！
ありがとうございました</span><img alt="🔥" draggable="false" src="https://abs-0.twimg.com/emoji/v2/svg/1f525.svg" title="Fire" class="r-4qtqp9 r-dflpy8 r-sjv1od r-zw8f10 r-10akycc r-h9hxbl"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">

</span><span class="r-18u37iz"><a dir="ltr" href="/hashtag/fleufleu?src=hashtag_click" role="link" class="css-4rbku5 css-18t94o4 css-901oao css-16my406 r-1cvl2hr r-1loqt21 r-poiln3 r-bcqeeo r-qvutc0">#fleufleu</a></span></div><div class="css-1dbjc4n"><div aria-label="13 replies, 11 Retweets, 94 likes, Liked" role="group" class="css-1dbjc4n r-1p0l6em r-18u37iz r-1wtj0ep r-rpnbwx r-1mdbhws" id="id__hqosci0mf3e"><div class="css-1dbjc4n r-18u37iz r-1h0z5md"><div aria-label="13 Replies. Reply" role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1777fci r-12sks89 r-1ny4l3l r-bztko3 r-lrvibr" data-testid="reply"><div dir="ltr" class="css-901oao r-1awozwy r-14j79pv r-6koalj r-37j5jr r-1inkyih r-16dba41 r-1h0z5md r-hbpseb r-bcqeeo r-o7ynqc r-clp7b1 r-3s2u2q r-qvutc0" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-xoduu5" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-1niwhzg r-sdzlij r-1p0dtai r-xoduu5 r-1d2f490 r-xf4iuw r-1ny4l3l r-u8s1d r-zchlnj r-ipm5af r-o7ynqc r-6416eg" data-gt2-color-override-ignore=""></div><svg viewBox="0 0 24 24" aria-hidden="true" class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi" data-gt2-color-override-ignore=""><g data-gt2-color-override-ignore=""><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z" data-gt2-color-override-ignore=""></path></g></svg></div><div class="css-1dbjc4n r-xoduu5 r-1udh08x" data-gt2-color-override-ignore=""><span data-testid="app-text-transition-container" style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);" data-gt2-color-override-ignore=""><span class="css-901oao css-16my406 r-poiln3 r-1b43r93 r-14yzgew r-1buqboj r-1orpq53 r-qvutc0" data-gt2-color-override-ignore=""><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0" data-gt2-color-override-ignore="">13</span></span></span></div></div></div></div><div class="css-1dbjc4n r-18u37iz r-1h0z5md"><div aria-expanded="false" aria-haspopup="menu" aria-label="11 Retweets. Retweet" role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1777fci r-12sks89 r-1ny4l3l r-bztko3 r-lrvibr" data-testid="retweet"><div dir="ltr" class="css-901oao r-1awozwy r-14j79pv r-6koalj r-37j5jr r-1inkyih r-16dba41 r-1h0z5md r-hbpseb r-bcqeeo r-o7ynqc r-clp7b1 r-3s2u2q r-qvutc0" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-xoduu5" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-1niwhzg r-sdzlij r-1p0dtai r-xoduu5 r-1d2f490 r-xf4iuw r-1ny4l3l r-u8s1d r-zchlnj r-ipm5af r-o7ynqc r-6416eg" data-gt2-color-override-ignore=""></div><svg viewBox="0 0 24 24" aria-hidden="true" class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi" data-gt2-color-override-ignore=""><g data-gt2-color-override-ignore=""><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z" data-gt2-color-override-ignore=""></path></g></svg></div><div class="css-1dbjc4n r-xoduu5 r-1udh08x" data-gt2-color-override-ignore=""><span data-testid="app-text-transition-container" style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);" data-gt2-color-override-ignore=""><span class="css-901oao css-16my406 r-poiln3 r-1b43r93 r-14yzgew r-1buqboj r-1orpq53 r-qvutc0" data-gt2-color-override-ignore=""><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0" data-gt2-color-override-ignore="">11</span></span></span></div></div></div></div><div class="css-1dbjc4n r-18u37iz r-1h0z5md"><div aria-label="94 Likes. Liked" role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1777fci r-12sks89 r-1ny4l3l r-bztko3 r-lrvibr" data-testid="unlike"><div dir="ltr" class="css-901oao r-1awozwy r-6koalj r-37j5jr r-1inkyih r-16dba41 r-1h0z5md r-hbpseb r-bcqeeo r-o7ynqc r-clp7b1 r-3s2u2q r-qvutc0" style="color: rgb(249, 24, 128);" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-xoduu5" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-1niwhzg r-sdzlij r-1p0dtai r-xoduu5 r-1d2f490 r-xf4iuw r-1ny4l3l r-u8s1d r-zchlnj r-ipm5af r-o7ynqc r-6416eg" data-gt2-color-override-ignore=""></div><svg viewBox="0 0 24 24" aria-hidden="true" class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi" data-gt2-color-override-ignore=""><g data-gt2-color-override-ignore=""><path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12z" data-gt2-color-override-ignore=""></path></g></svg></div><div class="css-1dbjc4n r-xoduu5 r-1udh08x" data-gt2-color-override-ignore=""><span data-testid="app-text-transition-container" style="transition-property: transform; transition-duration: 0.3s; transform: translate3d(0px, 0px, 0px);" data-gt2-color-override-ignore=""><span class="css-901oao css-16my406 r-poiln3 r-1b43r93 r-14yzgew r-1buqboj r-1orpq53 r-qvutc0" data-gt2-color-override-ignore=""><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0" data-gt2-color-override-ignore="">94</span></span></span></div></div></div></div><div class="css-1dbjc4n r-18u37iz r-1h0z5md"><div aria-expanded="false" aria-haspopup="menu" aria-label="Share Tweet" role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-1777fci r-12sks89 r-1ny4l3l r-bztko3 r-lrvibr"><div dir="ltr" class="css-901oao r-1awozwy r-14j79pv r-6koalj r-37j5jr r-1inkyih r-16dba41 r-1h0z5md r-hbpseb r-bcqeeo r-o7ynqc r-clp7b1 r-3s2u2q r-qvutc0" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-xoduu5" data-gt2-color-override-ignore=""><div class="css-1dbjc4n r-1niwhzg r-sdzlij r-1p0dtai r-xoduu5 r-1d2f490 r-xf4iuw r-1ny4l3l r-u8s1d r-zchlnj r-ipm5af r-o7ynqc r-6416eg" data-gt2-color-override-ignore=""></div><svg viewBox="0 0 24 24" aria-hidden="true" class="r-4qtqp9 r-yyyyoo r-1xvli5t r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1hdv0qi" data-gt2-color-override-ignore=""><g data-gt2-color-override-ignore=""><path d="M17.53 7.47l-5-5c-.293-.293-.768-.293-1.06 0l-5 5c-.294.293-.294.768 0 1.06s.767.294 1.06 0l3.72-3.72V15c0 .414.336.75.75.75s.75-.336.75-.75V4.81l3.72 3.72c.146.147.338.22.53.22s.384-.072.53-.22c.293-.293.293-.767 0-1.06z" data-gt2-color-override-ignore=""></path><path d="M19.708 21.944H4.292C3.028 21.944 2 20.916 2 19.652V14c0-.414.336-.75.75-.75s.75.336.75.75v5.652c0 .437.355.792.792.792h15.416c.437 0 .792-.355.792-.792V14c0-.414.336-.75.75-.75s.75.336.75.75v5.652c0 1.264-1.028 2.292-2.292 2.292z" data-gt2-color-override-ignore=""></path></g></svg></div></div></div></div></div></div></div></div></div></div></div></div></article></div></div></div>```


Thanks for your patience! I really don't know what I'm doing.

PS: this missing Translate button is exactly the same on my laptop and pc...they both have Windows Pro 21H2, all updates etc, Firefox 98.0.1 on the laptop and Firefox ESR 91 on the Desktop.

**Comment by Harumoon** [comment]
[AA.txt](https://github.com/Bl4Cc4t/GoodTwitter2/files/8319570/AA.txt)

**Comment by Harumoon** [comment]
Thanks for our patience, I have no idea what I'm doing here. In case that didn't work, here's the txt file of it

[AA.txt](https://github.com/Bl4Cc4t/GoodTwitter2/files/8319584/AA.txt)
.

**Comment by Harumoon** [comment]
It's the same on Chrome browser too, I've tried FF, Edge and Chrome, there's no Translate button on any of them, eg: the tweet below is from Chrome on the Desktop pc. 

![Capture](https://user-images.githubusercontent.com/101605071/159383029-f58d8f3e-051a-46df-bee0-6f7d24c868cd.JPG)

**Comment by Harumoon** [comment]
If I open the actual Tweet, of course the button is there, which is just how it works without GT2 anyway.

![Capture b](https://user-images.githubusercontent.com/101605071/159383681-84cad538-71d4-4896-985d-736f3cd4f7c5.JPG)

**Comment by Bl4Cc4t** [comment]
hm, the node you sent looks normal, it should be detected. what language string do you have?

you can find that out by clicking "view page source". just make a screenshot of the first bit, like this:
![image](https://user-images.githubusercontent.com/6740726/159705124-c98987e9-2173-4667-86fc-4d22a533fd36.png)

I suspect it is some kind of special string or it may even be missing which causes this issue.

**Comment by Harumoon** [comment]
Thanks for all the help, the 'view page source' looks different from yours but the top bit is as in the screenshot here. Language seems to be the same as yours, English? Up until a few days ago this all used to work perfectly, and as far as I know nothing was changed at all...the Translate button just suddenly disappeared one day.

![Capture](https://user-images.githubusercontent.com/101605071/159801952-b331a398-6fec-4af9-8c0b-d3acab10c900.JPG)

**Comment by Aridow** [comment]
Don't know if it has something to do with it: I have the translate button with v0.0.37, but when I click on it, it opens the tweet instead of translating it. If the tweet is already opened, it translated it.

**Comment by Kosouda** [comment]
> Don't know if it has something to do with it: I have the translate button with v0.0.37, but when I click on it, it opens the tweet instead of translating it. If the tweet is already opened, it translates it.

I came here to report exactly this.  I think I also had the issue of Translate Tweet missing several days ago, but it magically fixed itself in a couple days, but then this new issue cropped up, where the post opens when clicking on Translate Tweet instead of just translating.  I think this new issue started just 2 or 3 days ago.

**Comment by Bl4Cc4t** [comment]
@Aridow @Kosouda I don't think this is related to this issue, I opened a new issue for that error: #425 
I think I can fix that one at least

**Comment by Kosouda** [comment]
Cool, thanks for your continued work on this!  Always appreciated.
I wish I could say how the missing Translate Tweet fixed itself for me.  I wonder if perhaps it was never truly missing for me, and my browser was just lagging really hard somehow.  I don't know.

**Comment by Harumoon** [comment]
Today I suddenly have the Translate button back but it's opening the tweet now, as the people above have mentioned. I see that it says this issue has been fixed, do I need to do something to apply the fix or something? I've tried disabling Violent Monkey then re-enabling it and reinstall GT2 but that doesn't change it. Same with Tampermonkey.

**Comment by Kosouda** [comment]
I think he means that it's fixed in the next version to be released but it hasn't been released yet because he wants to include other fixes.

**Comment by Harumoon** [comment]
Ah I see, thanks

**Comment by Bl4Cc4t** [comment]
@Kosouda @Harumoon Hm, I still do not understand why it was missing in the first place, but at least that issue wasn't permanent if you both got it back. 
I suspect some kind of per-user testing/changes coming from twitters end were the reason it was missing, but I am not sure.

and yeah, lots of people are confused why the issue says "fixed" but actually isn't and if they need to manually change something... I think I'll just rename the green tag to "fixed for next update" or something, maybe that reduces the confusion a bit :D

**Comment by Harumoon** [comment]
Ok thanks a lot

**Comment by Kosouda** [comment]
I wish I could say I did anything that might have caused it to either disappear or reappaer, but there really was nothing.  Fortunately it was very brief, so yeah, I agree with the guess that it was some botched rollout thing for god-knows-what with Twitter, maybe changing Translate Tweet from text to an icon in the future?  Who knows.

**Comment by Bl4Cc4t** [comment]
I'll close this one for now, if something like this happens again, please open a new issue :)
