### ISSUE TITLE
GoodTwitter2 doesn't work and sometimes leaves with this.

### ISSUE THREAD

**Issue by m3k1e** [Bl4Cc4t/GoodTwitter2#547]
I have no words to say this.
![chrome_Wbl2o5iVii](https://user-images.githubusercontent.com/41316133/230701357-5c85fa92-adbf-41c1-a195-2d09aba1702a.png)

**Comment by Bl4Cc4t** [comment]
Some words would be helpful though, for example the version of the script you're using.
This exact issue has happened with the previous one, v0.0.44. The last update, v0.0.44.1 fixed this issue.

Please reply with your version so we know it's not that issue that is already fixed!

**Comment by m3k1e** [comment]
It's fixed now in v0.0.44.1. Thanks!

**Comment by NoThanksPal** [comment]
Hi, I am still having this issue on v0.0.44.1 on Chrome Version 111.0.5563.148 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/66384542/231180225-b9b8e07e-be73-483f-ac26-e45c9200cb7a.png)

**Comment by Bl4Cc4t** [comment]
@NoThanksPal are some other things on the site glitching out too or is it just that sidebar element that misbehaves (and the avatar on the navbar on that note)?

**Comment by Bl4Cc4t** [comment]
okay that's good, this will be an easy fix then :)

**Comment by LegoLoco7** [comment]
I'm using LibreWolf (a fork of Firefox) and Tampermonkey, and recently GoodTwitter2 hasn't been working at all. It was working for a while, but at some point, it stopped working, and I nearly forgot about it. I have other extensions, but because I haven't added many since it was previously working, I don't think they're the issue.

**Comment by Bl4Cc4t** [comment]
@LegoLoco7 I'm not sure what's going on there, but I created a new issue for this as seen above.
It indeed doesn't even give me an error message to work with...

**Comment by Bl4Cc4t** [comment]
broken for firefox 112 as well it seems.
