### ISSUE TITLE
J/K keyboard hotkey doesn't properly scroll when a tweet is selected

### ISSUE THREAD

**Issue by SCOTT0852** [Bl4Cc4t/GoodTwitter2#568]
**Please check the following before you continue**
- [Typescript beta, but it happens on the JS version too] Bug happens with the newest version of GT2 (see the [changelog](https://github.com/Bl4Cc4t/GoodTwitter2/blob/master/doc/changelog.md))
- [Yep] Checked [FAQ](https://github.com/Bl4Cc4t/GoodTwitter2#faq)
- [As far as I can tell] Checked if the issue has not been reported before

**Describe the bug**
What sites does it affect?
The J and K keyboard shortcuts are supposed to select the next and previous tweet on screen respectively. They still do this with GT2, but it doesn't work when you click on a tweet (possibly due to the "Tweet" heading bar with the back arrow). It does work properly on the main timeline and profile pages, although it acts differently on both - on profile pages the tweet snaps all the way to the top, while on the timeline there's a gap between the top and the highlighted tweet.
Stock Twitter behavior is to snap the tweet as high as it can go while making sure that heading bars such as the "Tweet" bar or the timeline's "For You/Following" bar do not cover it.

**Screenshots**
For display issues, adding screenshots or even videos of your screen is recommended.
Scrolling down to a reply with only one line of text:
![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/33875157/180a25ca-8d17-41b6-ae53-cf3f130846a6)
Attempting to scroll all the way up to the main tweet with K does not go all the way (art by onebadnoodle_):
![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/33875157/7bed6e38-95c1-42f2-b322-2f9a5e7768c3)

Stock Twitter for reference - the image is snapped as high as possible and not covered:
![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/33875157/0a86f3ab-bb52-489b-a6b5-8263675b9d65)

**Your configuration**
 - Browser - Firefox 116
 - Userscript Manager - Tampermonkey 4.19

**Comment by Bl4Cc4t** [comment]
Hm, I never used the shortcuts before. Should hopefully be easy to fix

**Comment by Bl4Cc4t** [comment]
Sorry for the long absence (again)

I just fixed this today.
see https://github.com/Bl4Cc4t/GoodTwitter2/releases/tag/v1.0.0-beta.2 for latest beta!

**Comment by SCOTT0852** [comment]
While it does work fine on the main timeline (alignment slightly off but I'm okay with that), it unfortunately still doesn't work in the replies to other tweets.
![image](https://github.com/Bl4Cc4t/GoodTwitter2/assets/33875157/2ff5d02b-9ebc-4dcd-90e9-4c2a2e44fe31)

**Comment by SCOTT0852** [comment]
never mind I clicked the readme install link to update and didn't realize it was still the old pre-typescript version, actually installing the right version works fine. sorry about that

**Comment by Bl4Cc4t** [comment]
Great to hear it works! Hopefully the new version will get more stable soon so I can replace some links to make it less confusing :D
